namespace NodeJS {
  interface ProcessEnv {
    IRON_SESSION_PWD: string;
    KAIJU_SAAS_WALLET_BASE_URL: string;
    KAIJU_TWITTER_AUTH_PROVIDER_ID: string;
    KAIJU_PROJECT_ACCESS_KEY: string;
    SESSION_COOKIE_NAME: string;
    XRPL_SERVER_URL: string;
    NEXT_PUBLIC_FIREBASE_APIKEY: string;
    NEXT_PUBLIC_FIREBASE_AUTHDOMAIN: string;
    NEXT_PUBLIC_FIREBASE_PROJECTID: string;
    NEXT_PUBLIC_FIREBASE_STORAGEBUCKET: string;
    NEXT_PUBLIC_FIREBASE_MESSAGINGSENDERID: string;
    NEXT_PUBLIC_FIREBASE_APPID: string;
  }
}
